var COLORS= [
{ rus: 'Белоснежный', eng: 'Snow', hex: 'FFFAFA' },
{ rus: 'Призрачно-белый', eng: 'Ghostwhite', hex: 'F8F8FF' },
{ rus: 'Белый-антик', eng: 'Antique White', hex: 'FAEBD7' },
{ rus: 'Кремовый', eng: 'Cream', hex: 'FFFBF0' },
{ rus: 'Персиковый', eng: 'Peachpuff', hex: 'FFDAB9' },
{ rus: 'Белый-навахо', eng: 'Navajo White', hex: 'FFDEAD' },
{ rus: 'Шелковый оттенок', eng: 'Cornsilk', hex: 'FFF8DC' },
{ rus: 'Слоновая кость', eng: 'Ivory', hex: 'FFFFF0' },
{ rus: 'Лимонный', eng: 'Lemon Chiffon', hex: 'FFFACD' },
{ rus: 'Морская раковина', eng: 'Seashell', hex: 'FFF5EE' },
{ rus: 'Медовый', eng: 'Honeydew', hex: 'F0FFF0' },
{ rus: 'Лазурный', eng: 'Azure', hex: 'F0FFFF' },
{ rus: 'Бледно-лиловый', eng: 'Lavender', hex: 'E6E6FA' },
{ rus: 'Голубой с красным отливом', eng: 'Lavender Blush', hex: 'FFF0F5' },
{ rus: 'Тускло-розовый', eng: 'Misty Rose', hex: 'FFE4E1' },
{ rus: 'Белый', eng: 'White (*)', hex: 'FFFFFF' },
{ rus: 'Черный', eng: 'Black (*)', hex: '000000' },
{ rus: 'Тускло-серый', eng: 'Dim Gray', hex: '696969' },
{ rus: 'Синевато-серый', eng: 'Slate Gray', hex: '708090' },
{ rus: 'Грифельно-серый', eng: 'Light Slate Gray', hex: '778899' },
{ rus: 'Серый', eng: 'Gray', hex: 'BEBEBE' },
{ rus: 'Светло-серый', eng: 'Light Gray', hex: 'C0C0C0' },
{ rus: 'Серый нейтральный', eng: 'Medium Gray', hex: 'A0A0A4' },
{ rus: 'Темно-серый', eng: 'Dark Gray', hex: '808080' },
{ rus: 'Полуночно-синий', eng: 'Midnight Blue', hex: '191970' },
{ rus: 'Темно-синий', eng: 'Navy(*), Dark Blue', hex: '000080' },
{ rus: 'Васильковый', eng: 'Cornflower', hex: '6495ED' },
{ rus: 'Грифельно-синий', eng: 'Slate Blue', hex: '6A5ACD' },
{ rus: 'Светлый грифельно-синий', eng: 'Light Slate Blue', hex: '8470FF' },
{ rus: 'Голубой королевский', eng: 'Royal Blue', hex: '4169E1' },
{ rus: 'Синий', eng: 'Blue', hex: '0000FF' },
{ rus: 'Небесно-голубой', eng: 'Sky Blue', hex: '87CEEB' },
{ rus: 'Небесно-голубой светлый', eng: 'Light Sky Blue', hex: '87CEFA' },
{ rus: 'Синий со стальным оттенком', eng: 'Steel Blue', hex: '4682B4' },
{ rus: 'Голубой со стальным оттенком', eng: 'Light Steel Blue', hex: 'B0C4DE' },
{ rus: 'Светло-синий', eng: 'Light Blue', hex: 'A6CAF0' },
{ rus: 'Синий с пороховым оттенком', eng: 'Powder Blue', hex: 'B0E0E6' },
{ rus: 'Бледно-бирюзовый', eng: 'Pale Turquoise', hex: 'AFEEEE' }, 
{ rus: 'Бирюзовый', eng: 'Turquoise', hex: '40E0D0' }, 
{ rus: 'Зеленовато-голубой', eng: 'Cyan (*)', hex: '00FFFF' },
{ rus: 'Светлый циан', eng: 'Light Cyan', hex: 'E0FFFF' },
{ rus: 'Темный циан', eng: 'Dark Cyan', hex: '008080' },
{ rus: 'Серо-синий', eng: 'Cadet Blue', hex: '5F9EA0' },
{ rus: 'Аквамарин', eng: 'Aquamarine', hex: '7FFFD4' },
{ rus: 'Цвет морской волны', eng: 'Seagreen', hex: '54FF9F' },
{ rus: 'Цвет морской волны, светлый', eng: 'Light Seagreen', hex: '20B2AA' },
{ rus: 'Бледно-зеленый', eng: 'Pale Green', hex: '98FB98' },
{ rus: 'Весенне-зеленый', eng: 'Spring Green', hex: '00FF7F' },
{ rus: 'Зеленая лужайка', eng: 'Lawn Green', hex: '7CFC00' },
{ rus: 'Зеленый', eng: 'Green (*)', hex: '00FF00' },
{ rus: 'Средне-зеленый', eng: 'Medium Green', hex: 'C0DCC0' },
{ rus: 'Темно-зеленый', eng: 'Dark Green', hex: '008000' },
{ rus: 'Зеленовато-желтый', eng: 'Chartreuse', hex: '7FFF00' },
{ rus: 'Зелено-желтый', eng: 'Green Yellow', hex: 'ADFF2F' },
{ rus: 'Лимонно-зеленый', eng: 'Lime Green', hex: '32CD32' },
{ rus: 'Желто-зеленый', eng: 'Yellow Green', hex: '9ACD32' },
{ rus: 'Зеленый лесной', eng: 'Forest Green', hex: '228B22' },
{ rus: 'Хаки', eng: 'Forest Green', hex: 'F0E68C' },
{ rus: 'Бледно-золотистый', eng: 'Pale Goldenrod', hex: 'EEE8AA' },
{ rus: 'Светло-желтый золотистый', eng: 'Light Goldenrod Yellow', hex: 'FAFAD2' },
{ rus: 'Светло-желтый', eng: 'Light Yellow', hex: 'FFFFE0' },
{ rus: 'Желтый', eng: 'Yellow (*)', hex: 'FFFF00' },
{ rus: 'Темно-желтый', eng: 'Dark Yellow', hex: '808000' },
{ rus: 'Золотой', eng: 'Gold', hex: 'FFD700' },
{ rus: 'Светло-золотистый', eng: 'Light Goldenrod', hex: 'FFEC8B' },
{ rus: 'Золотистый', eng: 'Goldenrod', hex: 'DAA520' },
{ rus: 'Желтоватый', eng: 'Burly Wood', hex: 'DEB887' },
{ rus: 'Розово-коричневый', eng: 'Rosy Brown', hex: 'BC8F8F' },
{ rus: 'Кожано-коричневый', eng: 'Saddle Brown', hex: '8B4513' },
{ rus: 'Охра', eng: 'Sienna', hex: 'A0522D' },
{ rus: 'Бежевый', eng: 'Beige', hex: 'F5F5DC' },
{ rus: 'Пшеничный', eng: 'Wheat', hex: 'F5DEB3' },
{ rus: 'Рыжевато-коричневый', eng: 'Tan', hex: 'D2B48C' },
{ rus: 'Шоколадный', eng: 'Chocolate', hex: 'D2691E' },
{ rus: 'Кирпичный', eng: 'Firebrick', hex: 'B22222' },
{ rus: 'Коричневый', eng: 'Brown', hex: 'A52A2A' },
{ rus: 'Сомон', eng: 'Salmon', hex: 'FA8072' },
{ rus: 'Светлый сомон', eng: 'Light Salmon', hex: 'FFA07A' },
{ rus: 'Оранжевый', eng: 'Orange', hex: 'FFA500' },
{ rus: 'Коралловый', eng: 'Coral', hex: 'FF7F50' },
{ rus: 'Коралловый светлый', eng: 'Light Coral', hex: 'F08080' },
{ rus: 'Оранжево-красный', eng: 'Orange Red', hex: 'FF4500' },
{ rus: 'Красный', eng: 'Red (*)', hex: 'FF0000' },
{ rus: 'Темно-красный', eng: 'Dark Red', hex: '800000' },
{ rus: 'Теплый розовый', eng: 'Hot Pink', hex: 'FF69B4' },
{ rus: 'Розовый', eng: 'Pink', hex: 'FFC0CB' },
{ rus: 'Светло-розовый', eng: 'Light Pink', hex: 'FFB6C1' },
{ rus: 'Красно-фиолетовый бледный', eng: 'Pale Violet Red', hex: 'DB7093' },
{ rus: 'Темно-бордовый', eng: 'Maroon (*)', hex: 'B03060' },
{ rus: 'Красно-фиолетовый', eng: 'Violet Red', hex: 'D02090' },
{ rus: 'Фуксин', eng: 'Magenta (*)', hex: 'FF00FF' },
{ rus: 'Фуксин темный', eng: 'Dark Magenta', hex: '800080' },
{ rus: 'Фиолетовый', eng: 'Violet', hex: 'EE82EE' },
{ rus: 'Темно-фиолетовый', eng: 'Plum', hex: 'DDA0DD' },
{ rus: 'Орсель', eng: 'Orchid', hex: 'DA70D6' },
{ rus: 'Фиолетово-синий', eng: 'Blue Violet', hex: '8A2BE2' }, 
{ rus: 'Пурпурный', eng: 'Purple', hex: 'A020F0' }
];